### ISSUE TITLE
No Number literal

### ISSUE THREAD

**Issue by dwijnand** [YoEight/deiko-config#10]
Given a HOCON config file like the following:

```hocon
foo {
  port: 1234
  addr: localhost
}
```

It looks like deiko-config misidentifies it as a string:

```haskell
*Data.Config> conf <- loadConfig "examples/baz.conf"
*Data.Config> reg = unConf conf
*Data.Config> regTypes reg
fromList [("foo",Object),("foo.addr",String),("foo.port",String)]
```

(For what it's worth, this is the logic that the reference Java implementation uses: https://github.com/lightbend/config/blob/v1.3.4/config/src/main/java/com/typesafe/config/impl/Tokenizer.java#L630-L631.)

**Comment by YoEight** [comment]
Thanks for reporting this. Let's see if I can push a patch for today

**Comment by YoEight** [comment]
Ok now that I re-read the code, as you figured it out, it only supports `String` literal internally.

```haskell
data Expr p t
    = ID Text
    | STRING Text
    | LIST [p t]
    | SUBST Text
    | MERGE (p t) (p t)
    | OBJECT [Prop p t] deriving Show

```

I let the user decide what kind of literal they want at call-site.

```haskell
getString :: MonadThrow m => Text -> Config -> m Text

getInteger :: MonadThrow m => Text -> Config -> m Integer

getBool :: MonadThrow m => Text -> Config -> m Bool

getParsec :: MonadThrow m
          => (forall s. Parsec Text s a)
          -> Text
          -> Config
          -> m a
```
Is there a problem with this approach for you?

**Comment by dwijnand** [comment]
Wow, thank you for getting back to me so quickly!

As an exercise, to continue my ramp up in Haskell, I've been trying to define an aeson `ToJson` instance for `Config` (https://twitter.com/ndm_haskell/status/1176014610488528897).

One of the issues I faced was in correctly mapping to JSON numbers.

I just pushed my branch (feel free to take anything useful):

https://github.com/YoEight/deiko-config/compare/master...dwijnand:to-aeson

I understand now how deiko-config is leaving that last bit of parsing to the user, so I guess I can reproduce what the java is doing...

**Comment by YoEight** [comment]
Adding `FromJSON` parsing out of `Config` should be straightforward. Don't forget I can help if you need it! The code hasn't been touch in 5 years but it still compiles with GHC 8.6.5 (Haven't tried on 8.8.1).

**Comment by dwijnand** [comment]
Thank you.

In terms of the originally opened issue here - there's no issue, just a misunderstanding.  So closing.

In terms of needing help: I do actually have a request.  Any chance you could change `Reg` so it doesn't contain:
* multiple entries for the same value; and
* fully-qualified keys at all levels?

Taking again the example

```hocon
foo {
  port: 1234
  addr: localhost
}
```

I'm seeing `regAST` contain the equivalent of

```
{ "foo": { "foo.port": "1234", "foo.addr": "localhost" }, "foo.port": "1234", "foo.addr": "localhost" }
```

instead of the simpler

```
{ "foo": { "port": "1234", "addr": "localhost" } }
```

(and then handling dot-separated lookups when they're made, in `getValue` perhaps.)

**Comment by YoEight** [comment]
>I'm seeing `regAST` contain the equivalent of
>
> ```
>{ "foo": { "foo.port": "1234", "foo.addr": "localhost" }, "foo.port": "1234", "foo.addr": "localhost" }
>```

Not exactly. What `regAST` contains is the following:

 ```
{ "foo": { "port": "1234", "addr": "localhost" }, "foo.port": "1234", "foo.addr": "localhost" }
```

>
>instead of the simpler
>
>```
>{ "foo": { "port": "1234", "addr": "localhost" } }
>```

To implement what you are asking for is simple, I just need to filter out every key that contains a dot.

**Comment by dwijnand** [comment]
Sadly that drops things like the key "another.string" in the app.conf example file.

**Comment by YoEight** [comment]
@dwijnand You can find the patch you need here #11 

Tell me if it meets your requirements there!
