### ISSUE TITLE
Updating dependencies/GHC

### ISSUE THREAD

**Issue by amilkov1** [YoEight/deiko-config#9]
Hey I [extended](https://github.com/amilkov3/confide) your lib to be able to derive record instances using `GHC.Generics`. Unfortunately I had some issues with dependencies since this lib hasn't been updated for GHC 8 and the dependencies are a little old as well, so i pulled in the source directly into my lib (i'll move to using `stack unpack` instead). Anyway It'd be sweet if you could update this that way I don't have to do that haha. Preciate your lib btw

**Comment by YoEight** [comment]
Hi @amilkov1,

Thanks for your words.

Sure thing I can update the lib to GHC 8. I try to get back to you later today.

**Comment by YoEight** [comment]
@amilkov1 It's done. I suppose you wanted it uploaded on Hackage right ?

**Comment by amilkov1** [comment]
@YoEight Yea putting it on Hackage would be great. Thanks a lot for the quick reply

**Comment by YoEight** [comment]
It was rhetorical, the new code is on Hackage already since this morning :-)
